#!/usr/bin/python3
# -*- coding: utf-8 -*-

import os
from PlaylistsManager import PlaylistsManagerPlayer, GarminPlaylistsManager

def test():
    manager = PlaylistsManagerPlayer(os.getcwd(), isCrLfNeeded=True)
    manager.removeCovers()
    manager.removePolishChars()
    manager.createPlaylists()

    folders=list()
    folders.append("Bachata")
    folders.append("Bachata Dominikana")
    manager.createGroupOfPlaylists("all", folders)

    manager.createTopOfMusic(30)

def main():
    manager = PlaylistsManagerPlayer(os.getcwd(), isCrLfNeeded=True)
    manager.check_missing_website()
    manager.removeCovers()
    manager.removePolishChars()
    manager.createPlaylists()

    folders=list()
    folders.append("Bachata")
    folders.append("cafe")
    folders.append("chillout")
    folders.append("Coldplay")
    folders.append("Czeslaw spiewa")
    folders.append("dance pop")
    folders.append("disco-polo")
    folders.append("electro Swing")
    folders.append("Empire of the Sun")
    folders.append("Happysad")
    folders.append("hip-hop")
    folders.append("imprezka")
    folders.append("Kizomba")
    folders.append("kizomba tradition")
    folders.append("Kortez")
    folders.append("latino")
    folders.append("Liber - Wczoraj I Dzis")
    folders.append("muzyka filmowa")
    folders.append("muzyka klasyczna")
    folders.append("Myslovitz")
    folders.append("Of Monsters and Men")
    folders.append("polskie hity")
    folders.append("positive chill")
    folders.append("Reggae")
    folders.append("relaks")
    folders.append("Rock-Electronic")
    folders.append("rock rap")
    folders.append("salsa")
    folders.append("spokojne-sad")
    folders.append("stare ale jare")
    folders.append("stare hity")
    folders.append("taniec")
    folders.append("techno")
    folders.append("UrbanKiz")
    manager.createGroupOfPlaylists("all", folders)

    folders=list()
    folders.append("dance pop")
    folders.append("imprezka")
    folders.append("positive chill")
    folders.append("relaks")
    folders.append("Rock-Electronic")
    folders.append("rock rap")
    folders.append("stare ale jare")
    folders.append("stare hity")
    folders.append("techno")
    manager.createGroupOfPlaylists("trening", folders)

    folders=list()
    folders.append("Bachata")
    folders.append("Kizomba")
    folders.append("kizomba tradition")
    folders.append("latino")
    folders.append("salsa")
    folders.append("taniec")
    folders.append("UrbanKiz")
    manager.createGroupOfPlaylists("taniec", folders)


    folders=list()
    folders.append("cafe")
    folders.append("chillout")
    folders.append("Coldplay")
    folders.append("Czeslaw spiewa")
    folders.append("dance pop")
    folders.append("electro Swing")
    folders.append("Empire of the Sun")
    folders.append("Happysad")
    folders.append("hip-hop")
    folders.append("imprezka")
    folders.append("Kortez")
    folders.append("latino")
    folders.append("Liber - Wczoraj I Dzis")
    folders.append("muzyka filmowa")
    folders.append("muzyka klasyczna")
    folders.append("Myslovitz")
    folders.append("Of Monsters and Men")
    folders.append("polskie hity")
    folders.append("positive chill")
    folders.append("Reggae")
    folders.append("relaks")
    folders.append("Rock-Electronic")
    folders.append("rock rap")
    folders.append("spokojne-sad")
    folders.append("stare ale jare")
    folders.append("stare hity")
    folders.append("taniec")
    folders.append("techno")
    manager.createGroupOfPlaylists("praca", folders)

    folders=list()
    folders.append("cafe")
    folders.append("chillout")
    folders.append("Coldplay")
    folders.append("Czeslaw spiewa")
    folders.append("Empire of the Sun")
    folders.append("Happysad")
    folders.append("hip-hop")
    folders.append("Kortez")
    folders.append("Liber - Wczoraj I Dzis")
    folders.append("muzyka filmowa")
    folders.append("muzyka klasyczna")
    folders.append("Myslovitz")
    folders.append("Of Monsters and Men")
    folders.append("polskie hity")
    folders.append("positive chill")
    folders.append("Reggae")
    folders.append("relaks")
    folders.append("Rock-Electronic")
    folders.append("spokojne-sad")
    manager.createGroupOfPlaylists("chilloutAll", folders)

    manager.createTopOfMusic(30)
    manager.createTopOfMusic(50)
    manager.createTopOfMusic(100)
    manager.createTopOfMusic(200)

    manager = GarminPlaylistsManager(os.getcwd(), isCrLfNeeded=True)
    manager.createPlaylistsAsGarmin("/home/bartosz/Music/Garmin5_music_128")
    #manager.checkDuplicates()

if __name__ == '__main__':
    main()

