version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.10.1
    steps:
      - checkout
      - run:
          command: |
            pip install -r requirements.txt
      - run:
          name: Running tests
          command: |
            coverage run -m pytest --junitxml=results/TestsReport.xml --html=results/TestsReport.html --self-contained-html tests/*
            coverage html
      - store_test_results:
          path: results
      - store_artifacts:
          path: results
