version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.10.1
    steps:
      - checkout
      - run:
          command: |
            pip install -r requirements.txt
      - run:
          name: Running tests
          command: |
            export PYTHONPATH=:
            coverage run -m pytest --html=htmlTests/TestsReport.html --self-contained-html tests/*
            coverage report
            coverage html
      - store_test_results:
          path: htmlTests
      - store_artifacts:
          path: htmlcov
