
class AlarmConfigFlask():
    ALARM_TIME =          "alarm_time"
    ALARM_MODE =          "alarm_mode"
    ALARM_MODE_NEWEST =   "newest_song"
    ALARM_MODE_PLAYLIST = "playlist"
    THE_NEWEST_SONG =     "theNewestSongChecked"
    PLAYLIST_CHECKED =    "playlistChecked"
    ALARM_PLAYLISTS =     "alarm_playlists"
    ALARM_PLATLIST_NAME = "alarm_playlist_name"
    ALARM_ACTIVE =        "alarm_active"
    MONDAY =    "monday_checked"
    TUESDAY =   "tuesday_checked"
    WEDNESDEY = "wednesday_checked"
    THURSDAY =  "thursday_checked"
    FRIDAY =    "friday_checked"
    SATURDAY =  "saturday_checked"
    SUNDAY =    "sunday_checked"
    MIN_VOLUME = "min_volume"
    MAX_VOLUME = "max_volume"
    DEFAULT_VOLUME = "default_volume"
    GROWING_VOLUME = "growing_volume"
    GROWING_SPEED =  "growing_speed"
    NEXT_ALARM = "next_alarm"
    NEXT_SNOOZE = "next_snooze"

class AlarmConfigLinux():
    THE_NEWEST_SONG =     "theNewestSongs"
    PLAYLIST =            "playlist"
    MIN_VOLUME =   "minVolume"
    MAX_VOLUME =   "maxVolume"
    DEFAULT_VOLUME = "defaultVolume"
    GROWING_VOLUME = "growingVolume"
    GROWING_SPEED =  "growingSpeed"

class SystemdCommand():
    START_ALARM_TIMER =     "sudo /bin/systemctl start alarm.timer"
    START_ALARM_SERVICE =   "sudo /bin/systemctl start alarm.service"
    STOP_ALARM_TIMER =      "sudo /bin/systemctl stop alarm.timer"
    STOP_ALARM_SNOOZE_TIMER =      "sudo /bin/systemctl stop alarm_snooze.timer"
    STATUS_ALARM_TIMER =    "sudo /bin/systemctl status alarm.timer"
    STATUS_ALARM_SNOOZE_TIMER =    "sudo /bin/systemctl status alarm_snooze.timer"
    STOP_ALARM_SERVICE =    "sudo /bin/systemctl stop alarm.service"
    ENABLE_ALARM_TIMER =    "sudo /bin/systemctl enable alarm.timer"
    DISABLE_ALARM_TIMER =   "sudo /bin/systemctl disable alarm.timer"
    DAEMON_RELOAD =         "sudo /bin/systemctl daemon-reload"
    IS_ACTIVE_ALARM_TIMER = "systemctl is-active alarm.timer"
    IS_ACTIVE_ALARM_SNOOZE_TIMER = "systemctl is-active alarm_snooze.timer"